plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tanjil.jarvis'
    compileSdk 35

    defaultConfig {
        applicationId "com.tanjil.jarvis"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "0.2"

        buildConfigField "String", "DEFAULT_API_URL", "\"https://ai.paidtoolbd.com\""
    }

    buildFeatures {
        buildConfig true
        viewBinding false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
